# Generated by Django 4.1.3 on 2023-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_choice_question_remove_quizscore_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
