# Generated by Django 4.1.3 on 2023-04-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_question_question_number'),
    ]

    operations = [
    ]
