# Generated by Django 4.1.3 on 2023-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
