# Generated by Django 4.1.3 on 2023-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_question_correct_code_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_code_snippet',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
