# Generated by Django 4.1.3 on 2023-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_score_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='programming_in_c_score',
            field=models.IntegerField(default=0),
        ),
    ]
