# Generated by Django 4.1.3 on 2023-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='num_correct',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='num_questions',
            field=models.PositiveIntegerField(),
        ),
    ]
